name: Cross Compile Test - Win64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


env:
  TMPPD: /tmp/pd
  OUTPATH: /tmp/pd-externals/



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: download pure-data
      run: |
        git clone https://github.com/pure-data/pure-data $TMPPD
    
    - name: install cross-compile tools
      run: |
        sudo apt-get install build-essential automake autoconf libtool gettext
        sudo apt-get install make gcc-mingw-w64-x86-64 gcc-mingw-w64-i686 mingw-w64 mingw-w64-tools
        sudo apt-get install nsis
      #sudo apt-get install make gcc-mingw-w64-x86-64 gcc-mingw-w64-i686 mingw-w64

    - name: compile Pd for Windows 64
      run: |
        cd $TMPPD
        ./autogen.sh
        ./configure --disable-asio --host=x86_64-w64-mingw32
        ls -a
        # make
        # ls -a




    # - name: make
    #   run: make
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
