name: Cross Compile Test - Win64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


env:
  TMPPD: /tmp/pd/
  OUTPATH: /tmp/pd-externals/



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: download pure-data
      run: |
        git clone https://github.com/pure-data/pure-data $TMPPD

    - name: install cross-compile tools
      run: |
        sudo apt-get install build-essential automake autoconf libtool gettext
        sudo apt-get install make gcc-mingw-w64-x86-64 gcc-mingw-w64-i686 mingw-w64 mingw-w64-tools
        sudo apt-get install nsis
      #sudo apt-get install make gcc-mingw-w64-x86-64 gcc-mingw-w64-i686 mingw-w64

    - name: preparing to compile Pd for Windows 64
      run: |
        cd $TMPPD
        wget http://msp.ucsd.edu/Software/pd-0.51-4.msw.zip
        unzip pd-0.51-4.msw.zip
        ls pd-0.51-4/
        # ./autogen.sh
        # ./configure --disable-asio --host=x86_64-w64-mingw32
    #
    # - name: compiling Pd for Windows 64
    #   run: |
    #     cd $TMPPD
    #     make
    #
    # - name: locating dlls
    #   run: |
    #     cd $TMPPD
    #     ls bin/* -a
    #     ls src/* -a

    # - name: cross-compiling library
    #   run: |
    #     make PLATFORM=x86_64-w64-mingw32 PDDIR=$TMPPD
    #     pwd
    #     # cd $GITHUB_WORKSPACE


    # - name: make
    #   run: make
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
